services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rastreamento
    ports:
      - "5432:5432"
    volumes:
      - posgres-data:/var/lib/postgresql/data

volumes:
  posgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data
      o: bind