/**
 * @fileoverview gRPC-Web generated client stub for rastreio
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: rastreio.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as rastreio_pb from './rastreio_pb'; // proto import: "rastreio.proto"


export class EstimativaEntregaClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCalcularEstimativa = new grpcWeb.MethodDescriptor(
    '/rastreio.EstimativaEntrega/CalcularEstimativa',
    grpcWeb.MethodType.UNARY,
    rastreio_pb.EstimativaRequest,
    rastreio_pb.EstimativaResponse,
    (request: rastreio_pb.EstimativaRequest) => {
      return request.serializeBinary();
    },
    rastreio_pb.EstimativaResponse.deserializeBinary
  );

  calcularEstimativa(
    request: rastreio_pb.EstimativaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rastreio_pb.EstimativaResponse>;

  calcularEstimativa(
    request: rastreio_pb.EstimativaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rastreio_pb.EstimativaResponse) => void): grpcWeb.ClientReadableStream<rastreio_pb.EstimativaResponse>;

  calcularEstimativa(
    request: rastreio_pb.EstimativaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rastreio_pb.EstimativaResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/rastreio.EstimativaEntrega/CalcularEstimativa',
        request,
        metadata || {},
        this.methodDescriptorCalcularEstimativa,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/rastreio.EstimativaEntrega/CalcularEstimativa',
    request,
    metadata || {},
    this.methodDescriptorCalcularEstimativa);
  }

}

